version: "3.10"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./backend/data/mongodb:/data/db
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend:/app
    ports:
      - "8001:8001"
    env_file:
      - .env
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8001
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
    env_file:
      - .env
    command: npm run dev