version: "3.10"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./backend/data/mongodb:/data/db
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8001:8000"
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB: mydatabase
      MONGO_USER: admin
      MONGO_PASSWORD: password
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000